source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RPServiceLayer_Example', :exclusive => true do
  pod "RPServiceLayer", :path => "../"
end

target 'RPServiceLayer_Tests', :exclusive => true do
  pod "RPServiceLayer", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
